/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Latihan4 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan4
     */
    public Latihan4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tkj = new javax.swing.JRadioButton();
        tek = new javax.swing.JCheckBox();
        design = new javax.swing.JCheckBox();
        exit = new javax.swing.JButton();
        erase = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        pro = new javax.swing.JCheckBox();
        rpl = new javax.swing.JRadioButton();
        ani = new javax.swing.JCheckBox();
        name = new javax.swing.JTextField();
        no = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hsl = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Biodata siswa");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 11, 110, 14);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 40, 70, 14);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 80, 70, 14);

        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 120, 60, 14);

        jLabel5.setText("Hobi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 160, 40, 14);

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));
        jPanel2.setLayout(null);

        buttonGroup1.add(tkj);
        tkj.setText("TKJ");
        tkj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkjActionPerformed(evt);
            }
        });
        jPanel2.add(tkj);
        tkj.setBounds(310, 120, 68, 23);

        tek.setText("Teknisi");
        tek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tekActionPerformed(evt);
            }
        });
        jPanel2.add(tek);
        tek.setBounds(240, 160, 80, 23);

        design.setText("Designer");
        jPanel2.add(design);
        design.setBounds(240, 190, 80, 23);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel2.add(exit);
        exit.setBounds(311, 220, 60, 23);

        erase.setText("Hapus");
        erase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseActionPerformed(evt);
            }
        });
        jPanel2.add(erase);
        erase.setBounds(210, 220, 90, 23);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel2.add(submit);
        submit.setBounds(110, 220, 90, 23);

        pro.setText("Programming");
        jPanel2.add(pro);
        pro.setBounds(110, 160, 100, 23);

        buttonGroup1.add(rpl);
        rpl.setText("RPL");
        jPanel2.add(rpl);
        rpl.setBounds(120, 120, 80, 23);

        ani.setText("Animator");
        jPanel2.add(ani);
        ani.setBounds(110, 190, 90, 23);
        jPanel2.add(name);
        name.setBounds(130, 40, 246, 30);
        jPanel2.add(no);
        no.setBounds(130, 80, 246, 30);

        jLabel6.setText("Hasil");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(70, 250, 50, 14);

        hsl.setColumns(20);
        hsl.setRows(5);
        jScrollPane1.setViewportView(hsl);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(70, 270, 310, 96);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 440, 380);

        setSize(new java.awt.Dimension(456, 419));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tkjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tkjActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
       String nama = name.getText();
       String absen = no.getText();
       String jurusan;
       String hobi = "";
       
       if(rpl.isSelected())
           jurusan="RPL";
       else if(tkj.isSelected())
           jurusan="TKJ";
       else
           jurusan = " ";
       
       if(pro.isSelected())
           hobi+=pro.getText()+" , ";
       if(ani.isSelected())
           hobi+=ani.getText()+" , ";
       if(tek.isSelected())
           hobi+=tek.getText()+" , ";
       if(design.isSelected())
           hobi+=design.getText()+" , ";
       hsl.setText("Nama siswa : "+nama+
               "\nAbsen siswa :  "+absen+
               "\nJurusan anda : "+jurusan+
               "\nHobi anda : "+hobi);
 
    }//GEN-LAST:event_submitActionPerformed

    private void tekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tekActionPerformed

    private void eraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseActionPerformed
        hsl.setText("");
        name.setText("");
        no.setText("");
        buttonGroup1.clearSelection();
        pro.setSelected(false);
        ani.setSelected(false);
        tek.setSelected(false);
        design.setSelected(false);
    }//GEN-LAST:event_eraseActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
  dispose();
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ani;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox design;
    private javax.swing.JButton erase;
    private javax.swing.JButton exit;
    private javax.swing.JTextArea hsl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField no;
    private javax.swing.JCheckBox pro;
    private javax.swing.JRadioButton rpl;
    private javax.swing.JButton submit;
    private javax.swing.JCheckBox tek;
    private javax.swing.JRadioButton tkj;
    // End of variables declaration//GEN-END:variables
}
